# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts to unit scale
#'
#' @param x the double to be converted
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a unit scale
#' @export
#' @useDynLib serosim2
toUnitScale <- function(x, min, max) {
    .Call('serosim2_toUnitScale', PACKAGE = 'serosim2', x, min, max)
}

