# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vector_sort <- function(x) {
    .Call('serosim2_vector_sort', PACKAGE = 'serosim2', x)
}

vector_order <- function(x) {
    .Call('serosim2_vector_order', PACKAGE = 'serosim2', x)
}

individual_sim <- function(mu_pars, tp_pars, m_pars, ti_pars, y0b, lower_titre_bound, times) {
    .Call('serosim2_individual_sim', PACKAGE = 'serosim2', mu_pars, tp_pars, m_pars, ti_pars, y0b, lower_titre_bound, times)
}

multiple_sim <- function(ti_pars, y0s, mu_pars, tp_pars, m_pars, times) {
    .Call('serosim2_multiple_sim', PACKAGE = 'serosim2', ti_pars, y0s, mu_pars, tp_pars, m_pars, times)
}

obs_error <- function(actual, obs, S, EA) {
    .Call('serosim2_obs_error', PACKAGE = 'serosim2', actual, obs, S, EA)
}

posterior_1 <- function(ti_pars, y0s, mu, cr_pars, tp_pars, m_pars, data, error_pars, mu_pop, mu_pop_sigma) {
    .Call('serosim2_posterior_1', PACKAGE = 'serosim2', ti_pars, y0s, mu, cr_pars, tp_pars, m_pars, data, error_pars, mu_pop, mu_pop_sigma)
}

posterior_2 <- function(ti_pars, y0s, mu, cr_pars, tp_pars, m_pars, data, pop_sigma, mu_pop, mu_pop_sigma, cr_pop, cr_sigmas) {
    .Call('serosim2_posterior_2', PACKAGE = 'serosim2', ti_pars, y0s, mu, cr_pars, tp_pars, m_pars, data, pop_sigma, mu_pop, mu_pop_sigma, cr_pop, cr_sigmas)
}

posterior_3 <- function(ti_pars, y0s, mu, cr_pars, tp_pars, m_pars, data, pop_sigma, mu_pop, mu_pop_sigma, cr_pop, m_pop, cr_sigmas, m_sigmas) {
    .Call('serosim2_posterior_3', PACKAGE = 'serosim2', ti_pars, y0s, mu, cr_pars, tp_pars, m_pars, data, pop_sigma, mu_pop, mu_pop_sigma, cr_pop, m_pop, cr_sigmas, m_sigmas)
}

#' Converts to unit scale
#'
#' @param x the double to be converted
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a unit scale
#' @export
#' @useDynLib serosim2
toUnitScale <- function(x, min, max) {
    .Call('serosim2_toUnitScale', PACKAGE = 'serosim2', x, min, max)
}

